name: Build Android AAB

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # ✅ Tạo keystore.jks từ base64 secret
      - name: Decode keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > app/keystore.jks

      # ✅ (Tuỳ chọn) Auto bump versionCode mỗi lần build
      # Nếu bạn muốn tự tăng thì bật step này, còn không thì xoá đi và tự sửa versionCode trong build.gradle
      - name: Auto bump versionCode (optional)
        run: |
          FILE="app/build.gradle"
          # lấy versionCode hiện tại
          VC=$(grep -oP 'versionCode\s+\K\d+' "$FILE" | head -n1)
          if [ -z "$VC" ]; then
            echo "Không tìm thấy versionCode trong $FILE"
            exit 1
          fi
          NEW_VC=$((VC+1))
          # replace versionCode
          sed -i "s/versionCode $VC/versionCode $NEW_VC/g" "$FILE"
          echo "Bumped versionCode: $VC -> $NEW_VC"
        shell: bash

      - name: Build AAB (Release)
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew :app:bundleRelease

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/*.aab
